# 22_multiturn

In [1]:
import pandas as pd

df = pd.read_parquet("/Users/rishitoshsingh/Documents/projects/applied/UserBench/data/travel22_multiturn/train.parquet")
df.head()

,data_source,prompt,ability,reward_model,extra_info
0,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['H...","{'index': 0, 'need_tools_kwargs': True, 'split..."
1,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['C...","{'index': 1, 'need_tools_kwargs': True, 'split..."
2,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['H...","{'index': 2, 'need_tools_kwargs': True, 'split..."
3,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['R...","{'index': 3, 'need_tools_kwargs': True, 'split..."
4,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['H...","{'index': 4, 'need_tools_kwargs': True, 'split..."

In [2]:
df.describe()

,data_source,prompt,ability,reward_model,extra_info
count,570,570,570,570,570
unique,1,570,1,570,570
top,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['H...","{'index': 0, 'need_tools_kwargs': True, 'split..."
freq,570,1,570,1,1

In [3]:
import pprint

In [7]:
i=0
pprint.pprint(df.iloc[i]["prompt"][0])
pprint.pprint(df.iloc[i]["prompt"][1])
pprint.pprint(df.iloc[i]["reward_model"])
pprint.pprint(df.iloc[i]["extra_info"])

{'content': 'You are an agent that actively interact with an specific '
            'environment. The followings are the details of the environment '
            'and your action space.\n'
            '\n'
            '- Environment Description: TravelGym is an environment where you '
            'interact with both a user and a search database to fulfill a '
            "travel plan. Since the user's initial intent may be incomplete, "
            'you must proactively elicit preferences, perform searches, and '
            'make informed recommendations.\n'
            '\n'
            '- Action Space: You should invocate the function '
            '`interact_with_env` to interact with the environment. The action '
            'should be one of the following: `search`, `action` or `answer`.\n'
            '\n'
            '- Action Description:\n'
            '  * `search`: If you choose `search`, you must issue a clear and '
            'detailed query to the database. Specify the travel aspect you are '
            'searching for (e.g., hotel, flight, etc.) and provide '
            'well-supported arguments for your query. Only make one focused '
            'search attempt at a time.\n'
            '  * `action`: If you choose `action`, you will communicate '
            "directly with the user. Your goal is to understand the user's "
            'preferences and intent by asking clear, specific questions. Avoid '
            'vague or overly general inquiries—focus on detailed aspects of '
            'their travel needs.\n'
            '  * `answer`: If you choose answer, you should recommend a '
            'specific option to the user by only providing its an option ID '
            'from the database in the content field, clearly tied to a '
            'particular travel aspect.\n'
            '\n'
            '- Important Notes:\n'
            '  * In each round of your interaction, you should analyze and '
            'carefully consider what to do next, and then invocate the '
            '`interact_with_env` tool to interact with the environment. You '
            'should provide your thought in each step when invocate the tool.\n'
            '  * The total number of rounds that you can interact with the '
            'environment is limited. You should smartly balance the number of '
            'rounds that you search, take action, or provide answer.\n'
            '  * Typically, you should start by performing a search, then take '
            "action to actively uncover the user's preferences or reason to "
            'provide an answer. Keep in mind that multiple travel aspects '
            'require answers, and while you may answer multiple times, each '
            'answer should include only one option ID.\n'
            '  * For each travel aspect, the user may have multiple '
            "preferences. What you ask may not directly align with the user's "
            'actual preferences, so you must proactively uncover them. '
            'Moreover, user preferences are often expressed implicitly, '
            'requiring careful interpretation.\n'
            '  * Be bold, creative and smart in your interaction with the '
            "environment! Let's begin!",
 'role': 'system'}
{'content': 'I am planning a trip from New York to San Francisco with a '
            'one-way flight on April 10th, and I will stay in a hotel in San '
            'Francisco from April 10th to April 15th.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}
{'env_name': 'TravelGym',
 'ground_truth': "['H11', 'F3']",
 'id': 'flight:2-37|hotel:2-9',
 'style': 'rule'}
{'index': 0,
 'need_tools_kwargs': True,
 'split': 'train',
 'tools_kwargs': {'interact_with_env': {'create_kwargs': {'env_name': 'TravelGym',
                                                          'id': 'flight:2-37|hotel:2-9'}}}}

In [13]:
i=1
pprint.pprint(df.iloc[i]["prompt"][0])
pprint.pprint(df.iloc[i]["prompt"][1])

{'content': 'You are an agent that actively interact with an specific '
            'environment. The followings are the details of the environment '
            'and your action space.\n'
            '\n'
            '- Environment Description: TravelGym is an environment where you '
            'interact with both a user and a search database to fulfill a '
            "travel plan. Since the user's initial intent may be incomplete, "
            'you must proactively elicit preferences, perform searches, and '
            'make informed recommendations.\n'
            '\n'
            '- Action Space: You should invocate the function '
            '`interact_with_env` to interact with the environment. The action '
            'should be one of the following: `search`, `action` or `answer`.\n'
            '\n'
            '- Action Description:\n'
            '  * `search`: If you choose `search`, you must issue a clear and '
            'detailed query to the database. Specify the travel aspect you are '
            'searching for (e.g., hotel, flight, etc.) and provide '
            'well-supported arguments for your query. Only make one focused '
            'search attempt at a time.\n'
            '  * `action`: If you choose `action`, you will communicate '
            "directly with the user. Your goal is to understand the user's "
            'preferences and intent by asking clear, specific questions. Avoid '
            'vague or overly general inquiries—focus on detailed aspects of '
            'their travel needs.\n'
            '  * `answer`: If you choose answer, you should recommend a '
            'specific option to the user by only providing its an option ID '
            'from the database in the content field, clearly tied to a '
            'particular travel aspect.\n'
            '\n'
            '- Important Notes:\n'
            '  * In each round of your interaction, you should analyze and '
            'carefully consider what to do next, and then invocate the '
            '`interact_with_env` tool to interact with the environment. You '
            'should provide your thought in each step when invocate the tool.\n'
            '  * The total number of rounds that you can interact with the '
            'environment is limited. You should smartly balance the number of '
            'rounds that you search, take action, or provide answer.\n'
            '  * Typically, you should start by performing a search, then take '
            "action to actively uncover the user's preferences or reason to "
            'provide an answer. Keep in mind that multiple travel aspects '
            'require answers, and while you may answer multiple times, each '
            'answer should include only one option ID.\n'
            '  * For each travel aspect, the user may have multiple '
            "preferences. What you ask may not directly align with the user's "
            'actual preferences, so you must proactively uncover them. '
            'Moreover, user preferences are often expressed implicitly, '
            'requiring careful interpretation.\n'
            '  * Be bold, creative and smart in your interaction with the '
            "environment! Let's begin!",
 'role': 'system'}
{'content': 'I am planning a trip to San Francisco from April 10th to April '
            '20th, staying in an apartment and renting a car for the duration '
            'of my stay.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}

In [14]:
i=1
pprint.pprint(df.iloc[i]["prompt"][1])
pprint.pprint(df.iloc[i+1]["prompt"][1])
pprint.pprint(df.iloc[i+2]["prompt"][1])
pprint.pprint(df.iloc[i+3]["prompt"][1])
pprint.pprint(df.iloc[i+4]["prompt"][1])

{'content': 'I am planning a trip to San Francisco from April 10th to April '
            '20th, staying in an apartment and renting a car for the duration '
            'of my stay.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}
{'content': 'I am planning a trip to Florence, Italy, staying in a hotel from '
            'April 15th to April 20th, and I will dine at a restaurant in the '
            'city on April 17th.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}
{'content': 'I am planning a business trip to San Francisco from November 15th '
            'to November 20th, requiring an apartment and restaurant visits in '
            'the city during this period.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}
{'content': 'I am planning a trip to Los Angeles from April 15th to April '
            '20th, during which I will stay in a hotel and rent a car.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}
{'content': 'I need a one-way flight from New York to Los Angeles on December '
            '15th and a rental car in Los Angeles from December 15th to '
            'December 22nd.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}

In [23]:
import pandas as pd

df = pd.read_parquet("/Users/rishitoshsingh/Documents/projects/applied/UserBench/data/travel22_multiturn/test.parquet")
df.head()

,data_source,prompt,ability,reward_model,extra_info
0,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['C...","{'index': 0, 'need_tools_kwargs': True, 'split..."
1,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['R...","{'index': 1, 'need_tools_kwargs': True, 'split..."
2,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['C...","{'index': 2, 'need_tools_kwargs': True, 'split..."
3,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['R...","{'index': 3, 'need_tools_kwargs': True, 'split..."
4,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['C...","{'index': 4, 'need_tools_kwargs': True, 'split..."

In [24]:
i=0
pprint.pprint(df.iloc[i]["prompt"][0])
pprint.pprint(df.iloc[i]["prompt"][1])
pprint.pprint(df.iloc[i]["reward_model"])
pprint.pprint(df.iloc[i]["extra_info"])

{'content': 'You are an agent that actively interact with an specific '
            'environment. The followings are the details of the environment '
            'and your action space.\n'
            '\n'
            '- Environment Description: TravelGym is an environment where you '
            'interact with both a user and a search database to fulfill a '
            "travel plan. Since the user's initial intent may be incomplete, "
            'you must proactively elicit preferences, perform searches, and '
            'make informed recommendations.\n'
            '\n'
            '- Action Space: You should invocate the function '
            '`interact_with_env` to interact with the environment. The action '
            'should be one of the following: `search`, `action` or `answer`.\n'
            '\n'
            '- Action Description:\n'
            '  * `search`: If you choose `search`, you must issue a clear and '
            'detailed query to the database. Specify the travel aspect you are '
            'searching for (e.g., hotel, flight, etc.) and provide '
            'well-supported arguments for your query. Only make one focused '
            'search attempt at a time.\n'
            '  * `action`: If you choose `action`, you will communicate '
            "directly with the user. Your goal is to understand the user's "
            'preferences and intent by asking clear, specific questions. Avoid '
            'vague or overly general inquiries—focus on detailed aspects of '
            'their travel needs.\n'
            '  * `answer`: If you choose answer, you should recommend a '
            'specific option to the user by only providing its an option ID '
            'from the database in the content field, clearly tied to a '
            'particular travel aspect.\n'
            '\n'
            '- Important Notes:\n'
            '  * In each round of your interaction, you should analyze and '
            'carefully consider what to do next, and then invocate the '
            '`interact_with_env` tool to interact with the environment. You '
            'should provide your thought in each step when invocate the tool.\n'
            '  * The total number of rounds that you can interact with the '
            'environment is limited. You should smartly balance the number of '
            'rounds that you search, take action, or provide answer.\n'
            '  * Typically, you should start by performing a search, then take '
            "action to actively uncover the user's preferences or reason to "
            'provide an answer. Keep in mind that multiple travel aspects '
            'require answers, and while you may answer multiple times, each '
            'answer should include only one option ID.\n'
            '  * For each travel aspect, the user may have multiple '
            "preferences. What you ask may not directly align with the user's "
            'actual preferences, so you must proactively uncover them. '
            'Moreover, user preferences are often expressed implicitly, '
            'requiring careful interpretation.\n'
            '  * Be bold, creative and smart in your interaction with the '
            "environment! Let's begin!",
 'role': 'system'}
{'content': 'I am planning a family trip to Austin from November 10th to '
            'November 15th, staying in an apartment and renting a car for the '
            'entire duration.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}
{'env_name': 'TravelGym',
 'ground_truth': "['C16', 'A17']",
 'id': 'apartment:2-86|rental_car:2-60',
 'style': 'rule'}
{'index': 0,
 'need_tools_kwargs': True,
 'split': 'test',
 'tools_kwargs': {'interact_with_env': {'create_kwargs': {'env_name': 'TravelGym',
                                                          'id': 'apartment:2-86|rental_car:2-60'}}}}

# 444_multiturn

In [26]:
import pandas as pd

df = pd.read_parquet("/Users/rishitoshsingh/Documents/projects/applied/UserBench/data/travel444_multiturn/train.parquet")
df.head()

,data_source,prompt,ability,reward_model,extra_info
0,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['F...","{'index': 0, 'need_tools_kwargs': True, 'split..."
1,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['F...","{'index': 1, 'need_tools_kwargs': True, 'split..."
2,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['A...","{'index': 2, 'need_tools_kwargs': True, 'split..."
3,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['F...","{'index': 3, 'need_tools_kwargs': True, 'split..."
4,interact_travelgym,[{'content': 'You are an agent that actively i...,interaction,"{'env_name': 'TravelGym', 'ground_truth': '['F...","{'index': 4, 'need_tools_kwargs': True, 'split..."

In [27]:
i=0
pprint.pprint(df.iloc[i]["prompt"][0])
pprint.pprint(df.iloc[i]["prompt"][1])
pprint.pprint(df.iloc[i]["reward_model"])
pprint.pprint(df.iloc[i]["extra_info"])

{'content': 'You are an agent that actively interact with an specific '
            'environment. The followings are the details of the environment '
            'and your action space.\n'
            '\n'
            '- Environment Description: TravelGym is an environment where you '
            'interact with both a user and a search database to fulfill a '
            "travel plan. Since the user's initial intent may be incomplete, "
            'you must proactively elicit preferences, perform searches, and '
            'make informed recommendations.\n'
            '\n'
            '- Action Space: You should invocate the function '
            '`interact_with_env` to interact with the environment. The action '
            'should be one of the following: `search`, `action` or `answer`.\n'
            '\n'
            '- Action Description:\n'
            '  * `search`: If you choose `search`, you must issue a clear and '
            'detailed query to the database. Specify the travel aspect you are '
            'searching for (e.g., hotel, flight, etc.) and provide '
            'well-supported arguments for your query. Only make one focused '
            'search attempt at a time.\n'
            '  * `action`: If you choose `action`, you will communicate '
            "directly with the user. Your goal is to understand the user's "
            'preferences and intent by asking clear, specific questions. Avoid '
            'vague or overly general inquiries—focus on detailed aspects of '
            'their travel needs.\n'
            '  * `answer`: If you choose answer, you should recommend a '
            'specific option to the user by only providing its an option ID '
            'from the database in the content field, clearly tied to a '
            'particular travel aspect.\n'
            '\n'
            '- Important Notes:\n'
            '  * In each round of your interaction, you should analyze and '
            'carefully consider what to do next, and then invocate the '
            '`interact_with_env` tool to interact with the environment. You '
            'should provide your thought in each step when invocate the tool.\n'
            '  * The total number of rounds that you can interact with the '
            'environment is limited. You should smartly balance the number of '
            'rounds that you search, take action, or provide answer.\n'
            '  * Typically, you should start by performing a search, then take '
            "action to actively uncover the user's preferences or reason to "
            'provide an answer. Keep in mind that multiple travel aspects '
            'require answers, and while you may answer multiple times, each '
            'answer should include only one option ID.\n'
            '  * For each travel aspect, the user may have multiple '
            "preferences. What you ask may not directly align with the user's "
            'actual preferences, so you must proactively uncover them. '
            'Moreover, user preferences are often expressed implicitly, '
            'requiring careful interpretation.\n'
            '  * Be bold, creative and smart in your interaction with the '
            "environment! Let's begin!",
 'role': 'system'}
{'content': 'I am planning a trip to Paris from December 10th to December '
            '17th, starting with a one-way flight from New York to Paris on '
            'December 10th. I will stay at a hotel in Paris from December 10th '
            'to December 17th and dine at a restaurant in Paris on December '
            '11th.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}
{'env_name': 'TravelGym',
 'ground_truth': "['F16', 'R7', 'H14']",
 'id': 'flight:4-315|hotel:4-60|restaurant:4-81',
 'style': 'rule'}
{'index': 0,
 'need_tools_kwargs': True,
 'split': 'train',
 'tools_kwargs': {'interact_with_env': {'create_kwargs': {'env_name': 'TravelGym',
                                                          'id': 'flight:4-315|hotel:4-60|restaurant:4-81'}}}}

# 2222_multiturn

In [28]:
import pandas as pd

df = pd.read_parquet("/Users/rishitoshsingh/Documents/projects/applied/UserBench/data/travel2222_multiturn/train.parquet")
i=0
pprint.pprint(df.iloc[i]["prompt"][0])
pprint.pprint(df.iloc[i]["prompt"][1])
pprint.pprint(df.iloc[i]["reward_model"])
pprint.pprint(df.iloc[i]["extra_info"])

{'content': 'You are an agent that actively interact with an specific '
            'environment. The followings are the details of the environment '
            'and your action space.\n'
            '\n'
            '- Environment Description: TravelGym is an environment where you '
            'interact with both a user and a search database to fulfill a '
            "travel plan. Since the user's initial intent may be incomplete, "
            'you must proactively elicit preferences, perform searches, and '
            'make informed recommendations.\n'
            '\n'
            '- Action Space: You should invocate the function '
            '`interact_with_env` to interact with the environment. The action '
            'should be one of the following: `search`, `action` or `answer`.\n'
            '\n'
            '- Action Description:\n'
            '  * `search`: If you choose `search`, you must issue a clear and '
            'detailed query to the database. Specify the travel aspect you are '
            'searching for (e.g., hotel, flight, etc.) and provide '
            'well-supported arguments for your query. Only make one focused '
            'search attempt at a time.\n'
            '  * `action`: If you choose `action`, you will communicate '
            "directly with the user. Your goal is to understand the user's "
            'preferences and intent by asking clear, specific questions. Avoid '
            'vague or overly general inquiries—focus on detailed aspects of '
            'their travel needs.\n'
            '  * `answer`: If you choose answer, you should recommend a '
            'specific option to the user by only providing its an option ID '
            'from the database in the content field, clearly tied to a '
            'particular travel aspect.\n'
            '\n'
            '- Important Notes:\n'
            '  * In each round of your interaction, you should analyze and '
            'carefully consider what to do next, and then invocate the '
            '`interact_with_env` tool to interact with the environment. You '
            'should provide your thought in each step when invocate the tool.\n'
            '  * The total number of rounds that you can interact with the '
            'environment is limited. You should smartly balance the number of '
            'rounds that you search, take action, or provide answer.\n'
            '  * Typically, you should start by performing a search, then take '
            "action to actively uncover the user's preferences or reason to "
            'provide an answer. Keep in mind that multiple travel aspects '
            'require answers, and while you may answer multiple times, each '
            'answer should include only one option ID.\n'
            '  * For each travel aspect, the user may have multiple '
            "preferences. What you ask may not directly align with the user's "
            'actual preferences, so you must proactively uncover them. '
            'Moreover, user preferences are often expressed implicitly, '
            'requiring careful interpretation.\n'
            '  * Be bold, creative and smart in your interaction with the '
            "environment! Let's begin!",
 'role': 'system'}
{'content': 'I will fly one-way from New York to San Francisco on December '
            '10th, stay at a hotel and rent a car in San Francisco from '
            'December 10th to December 15th, and visit a restaurant in San '
            'Francisco on December 12th.\n'
            'Also my budget is limited so as long as my preferences are '
            'satisfied, I would also like to choose the cheapest option for '
            'each.\n',
 'role': 'user'}
{'env_name': 'TravelGym',
 'ground_truth': "['F19', 'C21', 'H6', 'R17']",
 'id': 'flight:2-48|hotel:2-29|rental_car:2-22|restaurant:2-33',
 'style': 'rule'}
{'index': 0,
 'need_tools_kwargs': True,
 'split': 'train',
 'tools_kwargs': {'interact_with_env': {'create_kwargs': {'env_name': 'TravelGym',
                                                          'id': 'flight:2-48|hotel:2-29|rental_car:2-22|restaurant:2-33'}}}}